import { AlertTriangle, ArrowDownToLine, Banknote, CheckCircle2, CircleDollarSign, CreditCard, Landmark, ReceiptText, Users } from "lucide-react";
import type { CashClosingSummary, PaymentNatureSummary } from "@/lib/treasury";
import { brl } from "@/lib/utils";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader } from "@/components/ui/card";

function PaymentIcon({ code }: { code: string }) { if (code === "DINHEIRO") return <Banknote size={16} className="text-blue-600"/>; if (code === "CARTAO") return <CreditCard size={16} className="text-blue-600"/>; if (code === "TRANSFERENCIA_CREDITO") return <Landmark size={16} className="text-blue-600"/>; if (code === "NOTAS") return <ReceiptText size={16} className="text-blue-600"/>; return <CircleDollarSign size={16} className="text-blue-600"/>; }

export function CashClosing({ data }: { data: CashClosingSummary }) {
  const available = data.turns > 0 || data.paymentMethods.length > 0;
  if (!available) return <Card className="mt-5"><CardContent className="grid h-40 place-items-center text-sm text-muted-foreground">Fechamento de caixa indisponível para o período.</CardContent></Card>;
  return <section className="mt-5" aria-label="Fechamento de caixa">
    <div className="mb-3 flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-semibold">Fechamento de caixa</h2><p className="text-xs text-muted-foreground">Apurado pelo WebPosto × apresentado na conferência. PIX integra Transferência bancária/Depósito.</p></div><Badge>{data.turns} caixas/turnos analisados</Badge></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
      <Summary label="Apurado" value={data.calculated} detail="Calculado pelo WebPosto" icon={CircleDollarSign}/>
      <Summary label="Apresentado" value={data.presented} detail="Informado na conferência" icon={CheckCircle2}/>
      <Summary label="Diferença" value={data.difference} detail="Apresentado menos apurado" icon={AlertTriangle} alert={Math.abs(data.difference) > 0.01}/>
      <Summary label="Sangria" value={data.sangria} detail="Retiradas durante o turno" icon={ArrowDownToLine}/>
    </div>
    <div className="mt-4 grid gap-5 xl:grid-cols-[1.65fr_1fr]">
      <Card><CardHeader><div><h3 className="font-semibold">Formas de recebimento</h3><p className="text-xs text-muted-foreground">Valores do fechamento; não representam créditos bancários liquidados.</p></div></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead><tr className="border-b text-left text-[11px] uppercase tracking-wide text-muted-foreground"><th className="pb-3">Forma</th><th className="pb-3 text-right">Apurado</th><th className="pb-3 text-right">Apresentado</th><th className="pb-3 text-right">Diferença</th><th className="pb-3 text-right">Situação</th></tr></thead><tbody>{data.paymentMethods.map(item => <PaymentRow key={item.code} item={item}/>)}</tbody></table></div></CardContent></Card>
      <Card><CardHeader><div><h3 className="font-semibold">Saídas do caixa</h3><p className="text-xs text-muted-foreground">Separadas das despesas gerenciais para impedir dupla contagem.</p></div></CardHeader><CardContent className="space-y-3"><OperationalLine icon={ReceiptText} label="Despesas do caixa/PDV" value={data.cashExpenses}/><OperationalLine icon={Users} label="Vale/adiantamento de funcionário" value={data.employeeAdvances}/><OperationalLine icon={AlertTriangle} label="Valor pendente de conferência" value={data.pending} alert/>{data.unavailableCompanies.length > 0 && <div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800">Sem fechamento disponível: {data.unavailableCompanies.join(", ")}.</div>}<p className="pt-2 text-[11px] leading-relaxed text-muted-foreground">Despesa do caixa reduz o dinheiro apurado. Ela só deve entrar novamente no relatório gerencial quando houver vínculo financeiro comprovado e deduplicado.</p></CardContent></Card>
    </div>
  </section>;
}

function Summary({ label, value, detail, icon: Icon, alert = false }: { label: string; value: number; detail: string; icon: typeof CircleDollarSign; alert?: boolean }) { return <Card className={alert ? "border-amber-300" : ""}><CardContent className="pt-5"><div className="flex items-center justify-between"><span className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</span><Icon size={18} className={alert ? "text-amber-600" : "text-blue-600"}/></div><strong className={alert ? "mt-3 block font-mono text-xl text-amber-700" : "mt-3 block font-mono text-xl"}>{brl(value)}</strong><p className="mt-1 text-[11px] text-muted-foreground">{detail}</p></CardContent></Card>; }
function PaymentRow({ item }: { item: PaymentNatureSummary }) { const divergent = Math.abs(item.difference) > 0.01; const manuallyConfirmed = item.items > 0 && item.humanConfirmed === item.items; const status = item.open ? `${item.open} revisar` : manuallyConfirmed ? "Conferido manualmente" : "Valores coincidem"; return <tr className="border-b last:border-0"><td className="py-3"><span className="flex items-center gap-2 font-medium"><PaymentIcon code={item.code}/>{item.label}</span><span className="ml-6 text-[10px] text-muted-foreground">{item.items} lançamentos</span></td><td className="py-3 text-right font-mono">{brl(item.calculated)}</td><td className="py-3 text-right font-mono">{brl(item.presented)}</td><td className={divergent ? "py-3 text-right font-mono font-semibold text-red-600" : "py-3 text-right font-mono text-emerald-600"}>{brl(item.difference)}</td><td className="py-3 text-right"><Badge className={item.open ? "bg-amber-500/10 text-amber-700" : manuallyConfirmed ? "bg-blue-500/10 text-blue-700" : "bg-emerald-500/10 text-emerald-700"}>{status}</Badge></td></tr>; }
function OperationalLine({ icon: Icon, label, value, alert = false }: { icon: typeof ReceiptText; label: string; value: number; alert?: boolean }) { return <div className={alert ? "flex items-center justify-between rounded-lg border border-amber-200 bg-amber-50 p-3" : "flex items-center justify-between rounded-lg border p-3"}><span className="flex items-center gap-2 text-sm"><Icon size={16} className={alert ? "text-amber-600" : "text-muted-foreground"}/>{label}</span><strong className="font-mono text-sm">{brl(value)}</strong></div>; }
