import { AlertTriangle, CheckCircle2, CircleHelp, LockKeyhole } from "lucide-react";
import type { CashDailySummary } from "@/lib/treasury";
import { brl, dateBr } from "@/lib/utils";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader } from "@/components/ui/card";

export function CashConsolidationStatus({ rows }: { rows: CashDailySummary[] }) {
  const consolidated = rows.reduce((sum, row) => sum + row.consolidated, 0); const pending = rows.reduce((sum, row) => sum + row.notConsolidated, 0); const unknown = rows.reduce((sum, row) => sum + row.consolidationUnknown, 0); const pendingValue = rows.reduce((sum, row) => sum + (row.notConsolidated ? row.calculated : 0), 0);
  return <Card className="mt-5"><CardHeader><div><div className="flex items-center gap-2"><LockKeyhole size={18} className="text-blue-600"/><h3 className="font-semibold">Consolidação operacional dos caixas</h3></div><p className="mt-1 text-xs text-muted-foreground">Estado oficial do fechamento no WebPosto, separado da conciliação financeira.</p></div><Badge>{rows.reduce((sum, row) => sum + row.turns, 0)} caixas/turnos</Badge></CardHeader><CardContent>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={CheckCircle2} label="Consolidados" value={String(consolidated)} tone="green"/><Metric icon={AlertTriangle} label="Não consolidados" value={String(pending)} tone="amber"/><Metric icon={CircleHelp} label="Status não informado" value={String(unknown)} tone="slate"/><Metric icon={AlertTriangle} label="Valor não consolidado" value={brl(pendingValue)} tone="red"/></div>
    <div className="mt-4 overflow-x-auto rounded-lg border"><table className="w-full min-w-[760px] text-sm"><thead className="bg-muted/60 text-left text-xs uppercase text-muted-foreground"><tr><th className="px-3 py-3">Data</th><th className="px-3 py-3">Unidade</th><th className="px-3 py-3 text-right">Turnos</th><th className="px-3 py-3 text-right">Valor apurado</th><th className="px-3 py-3">Consolidação WebPosto</th><th className="px-3 py-3">Conciliação financeira</th></tr></thead><tbody>{rows.map((row, index) => { const status = row.notConsolidated ? "Não consolidado" : row.consolidated ? "Consolidado" : "Não informado"; return <tr key={`${row.companyCode}-${row.date}-${index}`} className="border-t"><td className="px-3 py-3 font-mono">{dateBr(row.date)}</td><td className="px-3 font-medium">{row.company}</td><td className="px-3 text-right">{row.turns}</td><td className="px-3 text-right font-mono">{brl(row.calculated)}</td><td className="px-3"><Badge className={status === "Consolidado" ? "bg-emerald-500/10 text-emerald-700" : status === "Não consolidado" ? "bg-amber-500/10 text-amber-700" : "bg-slate-500/10 text-slate-600"}>{status}</Badge></td><td className="px-3"><Badge className={Math.abs(row.difference) <= .01 ? "bg-emerald-500/10 text-emerald-700" : "bg-red-500/10 text-red-700"}>{Math.abs(row.difference) <= .01 ? "Sem diferença" : `Diferença ${brl(row.difference)}`}</Badge></td></tr>; })}</tbody></table></div>
    {unknown > 0 && <p className="mt-3 text-xs text-muted-foreground">Quando a API não entrega um campo explícito de consolidação, o sistema mantém “Não informado” e não deduz o estado pelo valor financeiro.</p>}
  </CardContent></Card>;
}

function Metric({ icon: Icon, label, value, tone }: { icon: typeof CheckCircle2; label: string; value: string; tone: "green" | "amber" | "slate" | "red" }) { const colors = { green: "border-emerald-200 bg-emerald-50/50 text-emerald-700", amber: "border-amber-200 bg-amber-50/50 text-amber-700", slate: "bg-muted/30 text-muted-foreground", red: "border-red-200 bg-red-50/50 text-red-700" }; return <div className={`rounded-lg border p-3 ${colors[tone]}`}><div className="flex items-center justify-between"><span className="text-xs">{label}</span><Icon size={15}/></div><strong className="mt-1 block font-mono text-lg text-foreground">{value}</strong></div>; }
