"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowDown, ArrowUp, Banknote, Pencil, TriangleAlert } from "lucide-react";
import type { CashDailySummary } from "@/lib/treasury";
import { brl, dateBr } from "@/lib/utils";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader } from "@/components/ui/card";

type SortKey = "date" | "company" | "turns" | "calculated" | "presented" | "difference";
const DESTINATIONS: Record<string, string> = { BANCO: "Depositado em banco", COFRE: "Mantido no cofre", TESOURARIA: "Transferido à tesouraria", FUNDO_CAIXA: "Mantido como fundo de caixa", DESPESA_SANGRIA: "Utilizado em despesa/sangria", NAO_DEPOSITADO: "Ainda não depositado", OUTRO: "Outro destino" };

export function DailyCashAnalysis({ rows, start, end }: { rows: CashDailySummary[]; start: string; end: string }) {
  const router = useRouter();
  const [sort, setSort] = useState<SortKey>("date"); const [direction, setDirection] = useState<"asc" | "desc">("desc"); const [onlyDivergent, setOnlyDivergent] = useState(false);
  const [selected, setSelected] = useState<CashDailySummary | null>(null); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const daily = useMemo(() => { const map = new Map<string, CashDailySummary>(); for (const row of rows) { const key = `${row.companyCode}-${row.date}`; const current = map.get(key) || { ...row, calculated: 0, presented: 0, difference: 0, sangria: 0, turns: 0, candidateDeposit: 0, otherBankCredits: 0, candidateCount: 0 }; current.calculated += row.calculated; current.presented += row.presented; current.difference += row.difference; current.sangria += row.sangria; current.turns += row.turns; current.candidateDeposit += row.candidateDeposit; current.otherBankCredits += row.otherBankCredits; current.candidateCount += row.candidateCount; current.allocation = row.allocation || current.allocation; map.set(key, current); } return [...map.values()].filter(row => !onlyDivergent || Math.abs(row.difference) > 10).sort((a, b) => { const left = a[sort], right = b[sort]; const compared = typeof left === "number" && typeof right === "number" ? left - right : String(left).localeCompare(String(right), "pt-BR"); return direction === "asc" ? compared : -compared; }); }, [rows, sort, direction, onlyDivergent]);
  const totals = daily.reduce((acc, row) => ({ calculated: acc.calculated + row.calculated, presented: acc.presented + row.presented, difference: acc.difference + row.difference, turns: acc.turns + row.turns }), { calculated: 0, presented: 0, difference: 0, turns: 0 });
  function toggle(field: SortKey) { if (sort === field) setDirection(value => value === "asc" ? "desc" : "asc"); else { setSort(field); setDirection("asc"); } }
  async function save(formData: FormData) { if (!selected) return; setSaving(true); setMessage(""); const response = await fetch("/api/cash-destination", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ dataInicial: start, dataFinal: end, empresaCodigo: selected.companyCode, movementDate: selected.date, destination: formData.get("destination"), amount: Number(formData.get("amount") || 0), destinationDate: formData.get("destinationDate") || null, bankAccount: formData.get("bankAccount") || null, bankMovementCode: formData.get("bankMovementCode") || null, reference: formData.get("reference") || null, responsibleUser: formData.get("responsibleUser"), note: formData.get("note") || null }) }); setSaving(false); if (response.ok) { setMessage("Destino salvo e vinculado ao fechamento diário."); setSelected(null); router.refresh(); } else setMessage("Não foi possível salvar o destino."); }
  return <Card className="mt-5"><CardHeader><div><div className="flex items-center gap-2"><Banknote size={18} className="text-emerald-600"/><h3 className="font-semibold">Conferência diária de dinheiro em espécie</h3></div><p className="mt-1 text-xs text-muted-foreground">Apurado pelo WebPosto × apresentado pelos operadores, com revisão do destino do dinheiro.</p></div><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={onlyDivergent} onChange={event => setOnlyDivergent(event.target.checked)}/> Somente diferenças acima de R$ 10</label></CardHeader><CardContent>
    {message && <p className="mb-3 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{message}</p>}
    <div className="overflow-x-auto rounded-lg border"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-muted/60 text-left text-xs uppercase text-muted-foreground"><tr><Head label="Data" field="date" sort={sort} direction={direction} toggle={toggle}/><Head label="Unidade" field="company" sort={sort} direction={direction} toggle={toggle}/><Head label="Turnos" field="turns" sort={sort} direction={direction} toggle={toggle} right/><Head label="Espécie apurada" field="calculated" sort={sort} direction={direction} toggle={toggle} right/><Head label="Espécie apresentada" field="presented" sort={sort} direction={direction} toggle={toggle} right/><Head label="Diferença" field="difference" sort={sort} direction={direction} toggle={toggle} right/><th className="px-3 py-3">Destino informado</th><th className="px-3 py-3">Ação</th></tr></thead><tbody>{daily.map(row => <tr key={`${row.companyCode}-${row.date}`} className={Math.abs(row.difference) > 10 ? "border-t bg-red-50/60 dark:bg-red-950/20" : "border-t"}><td className="px-3 py-3 font-mono">{row.date ? dateBr(row.date) : "—"}</td><td className="px-3 font-medium">{row.company}</td><td className="px-3 text-right">{row.turns}</td><td className="px-3 text-right font-mono">{brl(row.calculated)}</td><td className="px-3 text-right font-mono">{brl(row.presented)}</td><td className={Math.abs(row.difference) > 10 ? "px-3 text-right font-mono font-semibold text-red-600" : "px-3 text-right font-mono text-emerald-600"}>{brl(row.difference)}</td><td className="px-3">{row.allocation ? <div><Badge className="bg-emerald-500/10 text-emerald-700">{DESTINATIONS[row.allocation.destination] || row.allocation.destination}</Badge><span className="mt-1 block font-mono text-xs">{brl(row.allocation.amount)}</span></div> : <Badge className="bg-amber-500/10 text-amber-700">Não informado</Badge>}</td><td className="px-3"><button onClick={() => { setSelected(row); setMessage(""); }} className="flex items-center gap-1 rounded-md border bg-background px-2.5 py-1.5 text-xs font-medium hover:bg-muted"><Pencil size={13}/>{row.allocation ? "Alterar" : "Revisar destino"}</button></td></tr>)}</tbody><tfoot><tr className="border-t-2 bg-muted/40 font-medium"><td colSpan={2} className="px-3 py-3">{daily.length} dias · {totals.turns} turnos</td><td/><td className="px-3 text-right font-mono">{brl(totals.calculated)}</td><td className="px-3 text-right font-mono">{brl(totals.presented)}</td><td className="px-3 text-right font-mono">{brl(totals.difference)}</td><td colSpan={2}/></tr></tfoot></table>{!daily.length && <div className="grid h-32 place-items-center text-sm text-muted-foreground">Nenhum fechamento em dinheiro para o filtro.</div>}</div>
    {selected && <form action={save} className="mt-4 rounded-xl border border-blue-200 bg-blue-50/50 p-4 dark:bg-blue-950/20"><div className="mb-3 flex items-start justify-between"><div><span className="text-xs font-semibold uppercase text-blue-600">Revisar destino do dinheiro</span><h4 className="font-semibold">{selected.company} · {dateBr(selected.date)} · {brl(selected.presented)}</h4></div><button type="button" onClick={() => setSelected(null)} className="text-xs text-muted-foreground">Fechar</button></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Field label="Destino"><select required name="destination" defaultValue={selected.allocation?.destination || ""} className="input"><option value="" disabled>Selecione</option>{Object.entries(DESTINATIONS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field><Field label="Valor destinado"><input required min="0" step="0.01" type="number" name="amount" defaultValue={selected.allocation?.amount ?? selected.presented} className="input"/></Field><Field label="Data do destino/depósito"><input type="date" name="destinationDate" defaultValue={selected.allocation?.destinationDate || selected.date} className="input"/></Field><Field label="Responsável"><input required minLength={2} name="responsibleUser" defaultValue={selected.allocation?.responsibleUser || ""} placeholder="Nome de quem conferiu" className="input"/></Field><Field label="Banco, conta ou cofre"><input name="bankAccount" defaultValue={selected.allocation?.bankAccount || ""} placeholder="Ex.: Banco do Brasil · Conta 123" className="input"/></Field><Field label="Código do movimento bancário"><input name="bankMovementCode" defaultValue={selected.allocation?.bankMovementCode || ""} placeholder="Selecione ou informe a referência" className="input"/></Field><Field label="Comprovante/referência"><input name="reference" defaultValue={selected.allocation?.reference || ""} placeholder="NSU, documento ou protocolo" className="input"/></Field><Field label="Observação"><input name="note" defaultValue={selected.allocation?.note || ""} placeholder="Explique diferenças ou destino parcial" className="input"/></Field></div><div className="mt-4 flex justify-end"><button disabled={saving} className="h-10 rounded-md bg-primary px-5 text-sm font-semibold text-primary-foreground disabled:opacity-50">{saving ? "Salvando..." : "Salvar destino"}</button></div></form>}
    <p className="mt-3 flex gap-2 rounded-lg bg-amber-50 p-3 text-xs text-amber-800 dark:bg-amber-950/20 dark:text-amber-300"><TriangleAlert size={15} className="shrink-0"/> Um destino informado não transforma automaticamente qualquer crédito em depósito. Banco, conta, referência e responsável preservam a trilha de auditoria.</p>
  </CardContent></Card>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1 text-xs font-medium">{label}{children}</label>; }
function Head({ label, field, sort, direction, toggle, right = false }: { label: string; field: SortKey; sort: SortKey; direction: "asc" | "desc"; toggle: (field: SortKey) => void; right?: boolean }) { return <th className={right ? "px-3 py-3 text-right" : "px-3 py-3"}><button onClick={() => toggle(field)} className={right ? "ml-auto flex items-center gap-1" : "flex items-center gap-1"}>{label}{sort === field && (direction === "asc" ? <ArrowUp size={12}/> : <ArrowDown size={12}/>)}</button></th>; }
