import { AlertTriangle, CalendarDays, CircleCheck, Clock3, ShieldAlert } from "lucide-react";
import type { TreasuryData } from "@/lib/treasury";
import { COMPANIES, DEPARTMENTS } from "@/lib/treasury";
import { brl, dateBr } from "@/lib/utils";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { KpiCard } from "./kpi-card";
import { CashFlowChart, CompositionChart, ForecastChart } from "./charts";
import { TransactionTable } from "./transaction-table";
import { ThemeToggle } from "./theme-toggle";
import { ExpenseClassification } from "./expense-classification";
import { CashClosing } from "./cash-closing";
import { CardCatalog } from "./card-catalog";
import { DailyCashAnalysis } from "./daily-cash-analysis";
import { CashConsolidationStatus } from "./cash-consolidation-status";
import { PresidentialResultBridge } from "./presidential-result-bridge";
interface Props { data: TreasuryData; start: string; end: string; company: string; department: string; basis: "caixa" | "competencia" }
export function ExecutiveDashboard({ data, start, end, company, basis }: Props) { const spark=data.flow.map(p=>p.balance).slice(-10); const alerts=[{level:"critical",icon:ShieldAlert,title:"Cobertura de caixa",detail:data.source==="unavailable"?"Fonte financeira indisponível":"Monitorar saldo projetado",impact:Math.abs(Math.min(data.kpis.projected,0)),days:0},{level:"warning",icon:AlertTriangle,title:"Liquidez operacional",detail:data.kpis.liquidity<1?"Créditos abaixo das saídas":"Liquidez dentro do esperado",impact:data.kpis.outflow,days:0},{level:"normal",icon:CircleCheck,title:"Conciliação",detail:"Acompanhar homologação departamental",impact:0,days:0}] as const; return <main className="min-w-0 flex-1 px-4 py-6 sm:px-6 xl:px-8"><header className="mb-6 flex flex-col justify-between gap-5 xl:flex-row xl:items-center"><div><div className="mb-2 flex items-center gap-2"><Badge className="bg-blue-500/10 text-blue-600">Enterprise Finance</Badge><span className="flex items-center gap-1 text-xs text-muted-foreground"><Clock3 size={13}/> {data.updatedAt ? new Date(data.updatedAt).toLocaleString("pt-BR") : "Aguardando atualização"}</span></div><h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">Tesouraria e Fluxo de Caixa</h1><p className="mt-1 text-sm text-muted-foreground">Visão executiva das três empresas licenciadas, sem consolidar departamentos indevidamente.</p></div><form className="flex flex-wrap items-end gap-2 rounded-lg border bg-card p-2 shadow-sm"><label className="grid gap-1 text-[11px] font-medium text-muted-foreground">INÍCIO<input name="start" type="date" defaultValue={start} className="h-9 rounded-md border bg-background px-2 text-sm text-foreground"/></label><label className="grid gap-1 text-[11px] font-medium text-muted-foreground">FIM<input name="end" type="date" defaultValue={end} className="h-9 rounded-md border bg-background px-2 text-sm text-foreground"/></label><label className="grid gap-1 text-[11px] font-medium text-muted-foreground">UNIDADE<select name="company" defaultValue={company} className="h-9 min-w-48 rounded-md border bg-background px-2 text-sm">{COMPANIES.map(c=><option key={c.code} value={c.code}>{c.name}</option>)}</select></label><label className="grid gap-1 text-[11px] font-medium text-muted-foreground">APURAÇÃO<select name="basis" defaultValue={basis} className="h-9 rounded-md border bg-background px-2 text-sm"><option value="competencia">Competência</option><option value="caixa">Caixa</option></select></label><button className="h-9 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground">Aplicar</button><ThemeToggle/></form></header>
  <form className="mb-5 flex flex-wrap items-center gap-3 rounded-lg border border-blue-200 bg-blue-50/50 p-3 dark:bg-blue-950/20"><input type="hidden" name="start" value={start}/><input type="hidden" name="end" value={end}/><input type="hidden" name="company" value={company}/><input type="hidden" name="basis" value={basis}/><label className="grid gap-1 text-[11px] font-semibold text-blue-700">DEPARTAMENTO<select name="department" defaultValue={data.selectedDepartment} className="h-9 min-w-64 rounded-md border bg-background px-2 text-sm text-foreground">{DEPARTMENTS.map(item => <option key={item.code} value={item.code}>{item.name}</option>)}</select></label><button className="mt-4 h-9 rounded-md bg-blue-600 px-4 text-sm font-medium text-white">Aplicar departamento</button><p className="text-xs text-muted-foreground">DRE e despesas seguem o departamento. Tesouraria permanece corporativa quando não possui vínculo comprovado.</p></form>
  <section aria-label="Indicadores financeiros" className="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><KpiCard label="Créditos bancários identificados" value={data.kpis.inflow} data={spark}/><KpiCard label="Saídas previstas" value={data.kpis.outflow} data={spark}/><KpiCard label="Saldo projetado" value={data.kpis.projected} data={spark}/><KpiCard label="Saldo acumulado" value={data.kpis.accumulated} data={spark}/><KpiCard label="Liquidez" value={data.kpis.liquidity} data={spark} kind="ratio"/></section>
  {data.units.length > 0 && <section aria-label="Comparativo das unidades" className="mt-5 grid gap-4 lg:grid-cols-3">{data.units.map(unit => <Card key={unit.code}><CardContent className="pt-5"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">{unit.name}</h2><Badge className={unit.available ? "bg-emerald-500/10 text-emerald-600" : "bg-red-500/10 text-red-600"}>{unit.available ? "Fonte disponível" : "Indisponível"}</Badge></div>{unit.available ? <div className="mt-4 grid grid-cols-3 gap-3 text-xs"><div><span className="text-muted-foreground">Créditos bancários</span><strong className="mt-1 block font-mono text-sm">{brl(unit.inflow)}</strong></div><div><span className="text-muted-foreground">Saídas previstas</span><strong className="mt-1 block font-mono text-sm">{brl(unit.outflow)}</strong></div><div><span className="text-muted-foreground">Saldo</span><strong className={unit.balance < 0 ? "mt-1 block font-mono text-sm text-critical" : "mt-1 block font-mono text-sm text-success"}>{brl(unit.balance)}</strong></div></div> : <p className="mt-4 text-xs text-muted-foreground">Esta unidade não entrou nos indicadores.</p>}</CardContent></Card>)}</section>}
  <div className="mt-4 flex flex-wrap items-center gap-2 text-xs text-muted-foreground"><span className="font-medium text-foreground">Origem homologada:</span>{data.sources.length ? data.sources.map(source => <Badge key={source}>{source.replaceAll("_", " ")}</Badge>) : <span>Nenhuma fonte disponível.</span>}</div>
  <PresidentialResultBridge lines={data.departmentalDre}/>
  <CashClosing data={data.cashClosing}/>
  <CashConsolidationStatus rows={data.cashClosing.dailyCash}/>
  <DailyCashAnalysis rows={data.cashClosing.dailyCash} start={start} end={end}/>
  <CardCatalog data={data.cardCatalog}/>
  <section className="mt-5 grid gap-5 xl:grid-cols-[1.65fr_1fr]"><Card><CardHeader><div><h2 className="font-semibold">Fluxo de caixa</h2><p className="text-xs text-muted-foreground">Créditos bancários identificados e saídas previstas</p></div><Badge>{dateBr(start)} — {dateBr(end)}</Badge></CardHeader><CardContent>{data.flow.length?<CashFlowChart data={data.flow}/>:<Empty/>}</CardContent></Card><Card><CardHeader><div><h2 className="font-semibold">Composição financeira</h2><p className="text-xs text-muted-foreground">Distribuição das movimentações, sem tratar crédito como faturamento</p></div></CardHeader><CardContent>{data.composition.some(i=>i.value)?<CompositionChart data={data.composition}/>:<Empty/>}</CardContent></Card></section>
  <section className="mt-5"><div className="mb-3 flex items-center justify-between"><div><h2 className="font-semibold">Alertas executivos</h2><p className="text-xs text-muted-foreground">Prioridades ordenadas por impacto financeiro</p></div></div><div className="grid gap-4 lg:grid-cols-3">{alerts.map(({level,icon:Icon,title,detail,impact,days})=><Card key={title} className={level==="critical"?"border-red-200":level==="warning"?"border-amber-200":"border-blue-200"}><CardContent className="pt-5"><div className="flex items-start justify-between"><span className={level==="critical"?"rounded-lg bg-red-50 p-2 text-red-600":level==="warning"?"rounded-lg bg-amber-50 p-2 text-amber-600":"rounded-lg bg-blue-50 p-2 text-blue-600"}><Icon size={19}/></span><Badge>{level}</Badge></div><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-1 text-sm text-muted-foreground">{detail}</p><div className="mt-4 flex justify-between border-t pt-3 text-xs"><span>Impacto <strong className="ml-1 font-mono text-foreground">{brl(impact)}</strong></span><span>{days} dias</span></div></CardContent></Card>)}</div></section>
  <Card className="mt-5"><CardHeader><div><h2 className="font-semibold">Movimentações financeiras</h2><p className="text-xs text-muted-foreground">Busca, risco e rastreabilidade por unidade</p></div></CardHeader><CardContent><TransactionTable rows={data.rows}/></CardContent></Card>
  <Card className="mt-5"><CardHeader><div><h2 className="font-semibold">Despesas gerenciais — regime solicitado: {basis === "caixa" ? "Caixa" : "Competência"}</h2><p className="text-xs text-muted-foreground">Separadas das despesas do caixa/PDV. A fonte atual é datada pela movimentação do ERP; registros sem data de pagamento comprovada não são promovidos artificialmente para regime de Caixa.</p></div><Badge>{data.expenses.length} registros</Badge></CardHeader><CardContent><ExpenseClassification rows={data.expenses} categories={data.expenseCategories}/></CardContent></Card>
  <Card className="mt-5"><CardHeader><div><h2 className="font-semibold">Previsão de liquidez</h2><p className="text-xs text-muted-foreground">Melhor cenário, esperado e pior cenário</p></div><CalendarDays className="text-muted-foreground" size={19}/></CardHeader><CardContent>{data.flow.some(item => item.expected !== null)?<ForecastChart data={data.flow}/>:<Empty message="A API ainda não forneceu uma projeção homologada."/>}</CardContent></Card>
  </main>; }
function Empty({ message = "A visualização será liberada quando a fonte estiver disponível." }: { message?: string }){return <div className="grid h-[280px] place-items-center rounded-lg border border-dashed bg-muted/20 text-center"><div><AlertTriangle className="mx-auto mb-2 text-muted-foreground"/><strong className="text-sm">Dados não homologados</strong><p className="mt-1 text-xs text-muted-foreground">{message}</p></div></div>}
