"use client";

import { useMemo, useState } from "react";
import { ArrowDown, ArrowUp, ChevronDown, ChevronRight, Search, SlidersHorizontal } from "lucide-react";
import type { TreasuryRow } from "@/lib/treasury";
import { brl, dateBr } from "@/lib/utils";
import { Badge } from "@/components/ui/badge";

type SortKey = keyof Pick<TreasuryRow, "date" | "dueDate" | "description" | "unit" | "category" | "value" | "risk">;
type GroupKey = "none" | "unit" | "category" | "risk";
const riskClass = { critical: "border-red-200 bg-red-50 text-red-700", warning: "border-amber-200 bg-amber-50 text-amber-700", normal: "border-blue-200 bg-blue-50 text-blue-700" };
const PAGE_SIZE = 20;

function isoDate(offset = 0) { const date = new Date(); date.setDate(date.getDate() + offset); return date.toISOString().slice(0, 10); }
function weekStart() { const date = new Date(); const day = date.getDay() || 7; date.setDate(date.getDate() - day + 1); return date.toISOString().slice(0, 10); }

export function TransactionTable({ rows }: { rows: TreasuryRow[] }) {
  const [query, setQuery] = useState(""); const [risk, setRisk] = useState("all"); const [category, setCategory] = useState("all"); const [unit, setUnit] = useState("all");
  const [movementStart, setMovementStart] = useState(""); const [movementEnd, setMovementEnd] = useState(""); const [dueStart, setDueStart] = useState(""); const [dueEnd, setDueEnd] = useState("");
  const [sort, setSort] = useState<SortKey>("date"); const [direction, setDirection] = useState<"asc" | "desc">("desc"); const [group, setGroup] = useState<GroupKey>("none"); const [open, setOpen] = useState<Set<string>>(new Set()); const [page, setPage] = useState(1);
  const categories = useMemo(() => [...new Set(rows.map(row => row.category))].sort(), [rows]); const units = useMemo(() => [...new Set(rows.map(row => row.unit))].sort(), [rows]);
  const filtered = useMemo(() => rows.filter(row => {
    const text = `${row.description} ${row.unit} ${row.category}`.toLowerCase();
    return text.includes(query.toLowerCase()) && (risk === "all" || row.risk === risk) && (category === "all" || row.category === category) && (unit === "all" || row.unit === unit)
      && (!movementStart || row.date >= movementStart) && (!movementEnd || row.date <= movementEnd)
      && (!dueStart || Boolean(row.dueDate) && row.dueDate! >= dueStart) && (!dueEnd || Boolean(row.dueDate) && row.dueDate! <= dueEnd);
  }).sort((a, b) => { const left = a[sort] ?? ""; const right = b[sort] ?? ""; const compared = typeof left === "number" && typeof right === "number" ? left - right : String(left).localeCompare(String(right), "pt-BR"); return direction === "asc" ? compared : -compared; }), [rows, query, risk, category, unit, movementStart, movementEnd, dueStart, dueEnd, sort, direction]);
  const totals = useMemo(() => ({ sum: filtered.reduce((sum, row) => sum + row.value, 0), count: filtered.length }), [filtered]);
  const pageRows = group === "none" ? filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE) : filtered;
  const grouped = useMemo(() => { const result = new Map<string, TreasuryRow[]>(); if (group === "none") return result; for (const row of filtered) { const key = String(row[group]); result.set(key, [...(result.get(key) || []), row]); } return result; }, [filtered, group]);
  function toggleSort(key: SortKey) { if (sort === key) setDirection(value => value === "asc" ? "desc" : "asc"); else { setSort(key); setDirection("asc"); } setPage(1); }
  function quick(range: "today" | "yesterday" | "week" | "month" | "30" | "next", target: "movement" | "due") { let start = "", end = ""; if (range === "today") start = end = isoDate(); if (range === "yesterday") start = end = isoDate(-1); if (range === "week") { start = weekStart(); end = isoDate(); } if (range === "month") { start = `${isoDate().slice(0, 8)}01`; end = isoDate(); } if (range === "30") { start = isoDate(-29); end = isoDate(); } if (range === "next") { start = isoDate(); end = isoDate(30); } if (target === "movement") { setMovementStart(start); setMovementEnd(end); } else { setDueStart(start); setDueEnd(end); } setPage(1); }
  const reset = () => { setQuery(""); setRisk("all"); setCategory("all"); setUnit("all"); setMovementStart(""); setMovementEnd(""); setDueStart(""); setDueEnd(""); setPage(1); };
  const allGroups = [...grouped.keys()];
  return <div>
    <div className="mb-4 rounded-xl border bg-muted/15 p-3">
      <div className="flex flex-wrap items-end gap-2"><label className="relative grid gap-1 text-[11px] font-medium text-muted-foreground"><span>BUSCA RÁPIDA</span><Search className="absolute bottom-2.5 left-3" size={15}/><input value={query} onChange={event => { setQuery(event.target.value); setPage(1); }} placeholder="Descrição, unidade..." className="h-9 w-64 rounded-md border bg-background pl-9 pr-3 text-sm text-foreground"/></label><Filter label="RISCO" value={risk} set={setRisk} options={["critical", "warning", "normal"]}/><Filter label="CATEGORIA" value={category} set={setCategory} options={categories}/><Filter label="UNIDADE" value={unit} set={setUnit} options={units}/><Filter label="AGRUPAR" value={group} set={value => { setGroup(value as GroupKey); setOpen(new Set()); }} options={["unit", "category", "risk"]}/><button onClick={reset} className="h-9 rounded-md border bg-background px-3 text-xs">Limpar filtros</button></div>
      <div className="mt-3 grid gap-3 xl:grid-cols-2"><DateFilter title="Data de movimento" start={movementStart} end={movementEnd} setStart={setMovementStart} setEnd={setMovementEnd} quick={range => quick(range, "movement")}/><DateFilter title="Data de vencimento" start={dueStart} end={dueEnd} setStart={setDueStart} setEnd={setDueEnd} quick={range => quick(range, "due")}/></div>
      {group !== "none" && <div className="mt-3 flex gap-2"><button onClick={() => setOpen(new Set(allGroups))} className="text-xs font-medium text-blue-600">Expandir todos</button><button onClick={() => setOpen(new Set())} className="text-xs font-medium text-muted-foreground">Recolher todos</button></div>}
    </div>
    <div className="overflow-x-auto rounded-lg border"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-muted/60 text-xs uppercase text-muted-foreground"><tr><Sortable label="Movimento" field="date" active={sort} direction={direction} onSort={toggleSort}/><Sortable label="Vencimento" field="dueDate" active={sort} direction={direction} onSort={toggleSort}/><Sortable label="Descrição" field="description" active={sort} direction={direction} onSort={toggleSort}/><Sortable label="Unidade" field="unit" active={sort} direction={direction} onSort={toggleSort}/><Sortable label="Categoria" field="category" active={sort} direction={direction} onSort={toggleSort}/><Sortable label="Valor" field="value" active={sort} direction={direction} onSort={toggleSort} right/><Sortable label="Risco" field="risk" active={sort} direction={direction} onSort={toggleSort}/></tr></thead><tbody>{group === "none" ? pageRows.map(row => <Row key={row.id} row={row}/>) : allGroups.map(key => { const items = grouped.get(key) || []; const expanded = open.has(key); const subtotal = items.reduce((sum, row) => sum + row.value, 0); return <FragmentGroup key={key} label={key} count={items.length} subtotal={subtotal} expanded={expanded} toggle={() => setOpen(current => { const next = new Set(current); if (expanded) next.delete(key); else next.add(key); return next; })} rows={items}/>; })}</tbody><tfoot><tr className="border-t-2 bg-muted/40 font-medium"><td colSpan={5} className="px-3 py-3">{totals.count} registros filtrados · Média {brl(totals.count ? totals.sum / totals.count : 0)}</td><td className="px-3 py-3 text-right font-mono">{brl(totals.sum)}</td><td/></tr></tfoot></table>{!filtered.length && <div className="grid h-32 place-items-center text-sm text-muted-foreground">Nenhuma movimentação corresponde aos filtros.</div>}</div>
    {group === "none" && <div className="mt-4 flex items-center justify-between text-xs text-muted-foreground"><span>Página {page} de {Math.max(1, Math.ceil(filtered.length / PAGE_SIZE))}</span><div className="flex gap-2"><button disabled={page === 1} onClick={() => setPage(value => value - 1)} className="rounded border px-3 py-1.5 disabled:opacity-40">Anterior</button><button disabled={page * PAGE_SIZE >= filtered.length} onClick={() => setPage(value => value + 1)} className="rounded border px-3 py-1.5 disabled:opacity-40">Próxima</button></div></div>}
  </div>;
}

function Filter({ label, value, set, options }: { label: string; value: string; set: (value: string) => void; options: string[] }) { return <label className="grid gap-1 text-[11px] font-medium text-muted-foreground"><span>{label}</span><select value={value} onChange={event => set(event.target.value)} className="h-9 max-w-52 rounded-md border bg-background px-2 text-sm text-foreground"><option value={label === "AGRUPAR" ? "none" : "all"}>{label === "AGRUPAR" ? "Sem agrupamento" : "Todos"}</option>{options.map(option => <option key={option} value={option}>{option.replaceAll("_", " ")}</option>)}</select></label>; }
type QuickRange = "today" | "yesterday" | "week" | "month" | "30" | "next";
function DateFilter({ title, start, end, setStart, setEnd, quick }: { title: string; start: string; end: string; setStart: (value: string) => void; setEnd: (value: string) => void; quick: (range: QuickRange) => void }) { return <fieldset className="rounded-lg border bg-background p-2"><legend className="px-1 text-[11px] font-semibold uppercase text-muted-foreground">{title}</legend><div className="flex flex-wrap items-center gap-2"><input aria-label={`${title} inicial`} type="date" value={start} onChange={event => setStart(event.target.value)} className="h-8 rounded border bg-background px-2 text-xs"/><input aria-label={`${title} final`} type="date" value={end} onChange={event => setEnd(event.target.value)} className="h-8 rounded border bg-background px-2 text-xs"/>{[["today","Hoje"],["yesterday","Ontem"],["week","Semana"],["month","Mês"],["30","30 dias"],["next","Próximos"]].map(([value, label]) => <button key={value} onClick={() => quick(value as QuickRange)} className="rounded-md bg-muted px-2 py-1 text-[11px] transition hover:bg-primary hover:text-primary-foreground">{label}</button>)}</div></fieldset>; }
function Sortable({ label, field, active, direction, onSort, right = false }: { label: string; field: SortKey; active: SortKey; direction: "asc" | "desc"; onSort: (key: SortKey) => void; right?: boolean }) { return <th className={right ? "px-3 py-3 text-right" : "px-3 py-3"}><button onClick={() => onSort(field)} className={right ? "ml-auto flex items-center gap-1" : "flex items-center gap-1"}>{label}{active === field ? direction === "asc" ? <ArrowUp size={13}/> : <ArrowDown size={13}/> : <SlidersHorizontal size={11} className="opacity-30"/>}</button></th>; }
function Row({ row }: { row: TreasuryRow }) { return <tr className="border-t transition hover:bg-muted/40"><td className="px-3 py-3 font-mono text-xs">{row.date ? dateBr(row.date) : "—"}</td><td className="px-3 font-mono text-xs">{row.dueDate ? dateBr(row.dueDate) : "—"}</td><td className="px-3 font-medium">{row.description}</td><td className="px-3 text-muted-foreground">{row.unit}</td><td className="px-3">{row.category}</td><td className="px-3 text-right font-mono">{brl(row.value)}</td><td className="px-3"><Badge className={riskClass[row.risk]}>{row.risk}</Badge></td></tr>; }
function FragmentGroup({ label, count, subtotal, expanded, toggle, rows }: { label: string; count: number; subtotal: number; expanded: boolean; toggle: () => void; rows: TreasuryRow[] }) { return <>{<tr className="border-t bg-muted/35"><td colSpan={7}><button onClick={toggle} className="flex w-full items-center gap-2 px-3 py-3 text-left font-semibold">{expanded ? <ChevronDown size={16}/> : <ChevronRight size={16}/>}<span>{label}</span><Badge>{count}</Badge><span className="ml-auto font-mono">{brl(subtotal)}</span></button></td></tr>}{expanded && rows.map(row => <Row key={row.id} row={row}/>)}</>; }
