"""Versoes explicitas dos contratos do motor de cadastro."""

from __future__ import annotations

REGISTRATION_REQUEST_SCHEMA_VERSION = "1.0.0"
REGISTRATION_RESULT_SCHEMA_VERSION = "1.0.0"
FISCAL_PROFILE_SCHEMA_VERSION = "1.0.0"
CHECKPOINT_SCHEMA_VERSION = "2.0.0"
CHECKPOINT_LEGACY_SCHEMA_VERSION = "1.0.0"
AUDIT_EVENT_SCHEMA_VERSION = "1.0.0"
POLICY_DECISION_SCHEMA_VERSION = "1.0.0"

ENGINE_VERSION = "1.0.0"
