"""
Catálogo de rotas INTEGRACAO mapeadas no cliente src/webposto + rotas usadas em diagnóstico.

Cada entrada pode ser executada pelo explorador (GET/POST/PUT conforme o campo method): o proxy
repassa à API WebPosto. Sucesso (200 etc.) depende da CHAVE, permissões, parâmetros e body.
"""

# flags: dates, pag, fil = auto-preenche dataInicial/dataFinal, pagina/tamanhoPagina, filial[]
# body = exige corpo JSON em POST/PUT
# path_params = substituir na URL na ordem (ex.: ["id"] para /CLIENTE/{id})

ENDPOINTS = [
    # —— Abastecimento ——
    {
        "categoria": "Abastecimento",
        "nome": "Listar abastecimentos",
        "method": "GET",
        "path": "/INTEGRACAO/ABASTECIMENTO",
        "dates": True,
        "pag": True,
        "fil": True,
        "extra": {"bico": "opcional — número do bico"},
    },
    {
        "categoria": "Abastecimento",
        "nome": "Encerrantes",
        "method": "GET",
        "path": "/INTEGRACAO/ABASTECIMENTO_ENCERRANTE",
        "dates": True,
        "pag": False,
        "fil": True,
    },
    {
        "categoria": "Abastecimento",
        "nome": "Divergências de abastecimento",
        "method": "GET",
        "path": "/INTEGRACAO/ABASTECIMENTO_DIVERGENCIA",
        "dates": True,
        "pag": False,
        "fil": True,
    },
    {
        "categoria": "Abastecimento",
        "nome": "Reajustar estoque combustível (PUT)",
        "method": "PUT",
        "path": "/INTEGRACAO/REAJUSTAR_ESTOQUE_PRODUTO_COMBUSTIVEL",
        "body": True,
        "aviso": "Altera estoque — use ambiente de testes.",
    },
    # —— Clientes / frota ——
    {
        "categoria": "Clientes",
        "nome": "Listar clientes",
        "method": "GET",
        "path": "/INTEGRACAO/CLIENTE",
        "dates": False,
        "pag": True,
        "fil": False,
        "extra": {"codigo": "", "cpfCnpj": "", "nome": ""},
    },
    {
        "categoria": "Clientes",
        "nome": "Criar cliente",
        "method": "POST",
        "path": "/INTEGRACAO/CLIENTE",
        "body": True,
        "aviso": "POST grava cadastro.",
    },
    {
        "categoria": "Clientes",
        "nome": "Atualizar cliente",
        "method": "PUT",
        "path": "/INTEGRACAO/CLIENTE/{id}",
        "path_params": ["id"],
        "body": True,
        "aviso": "PUT altera cadastro.",
    },
    {
        "categoria": "Clientes",
        "nome": "Frota (veículos por cliente)",
        "method": "GET",
        "path": "/INTEGRACAO/CLIENTE_FROTA",
        "dates": False,
        "pag": True,
        "fil": False,
        "extra": {"clienteCodigo": ""},
    },
    {
        "categoria": "Clientes",
        "nome": "Atualizar veículo frota",
        "method": "PUT",
        "path": "/INTEGRACAO/CLIENTE_FROTA_VEICULO/{cliente_codigo}/{cliente_veiculo_codigo}",
        "path_params": ["cliente_codigo", "cliente_veiculo_codigo"],
        "body": True,
    },
    {
        "categoria": "Clientes",
        "nome": "Grupos de clientes",
        "method": "GET",
        "path": "/INTEGRACAO/GRUPO_CLIENTE",
        "pag": True,
    },
    {
        "categoria": "Clientes",
        "nome": "Criar grupo cliente",
        "method": "POST",
        "path": "/INTEGRACAO/GRUPO_CLIENTE",
        "body": True,
    },
    {
        "categoria": "Clientes",
        "nome": "Atualizar grupo cliente",
        "method": "PUT",
        "path": "/INTEGRACAO/GRUPO_CLIENTE/{id}",
        "path_params": ["id"],
        "body": True,
    },
    {
        "categoria": "Clientes",
        "nome": "Vincular cliente × unidade negócio",
        "method": "POST",
        "path": "/INTEGRACAO/VINCULAR_CLIENTE_UNIDADE_NEGOCIO",
        "body": True,
    },
    {
        "categoria": "Clientes",
        "nome": "Integrar prazo cliente",
        "method": "POST",
        "path": "/INTEGRACAO/INTEGRACAO_CLIENTE_PRAZO",
        "body": True,
    },
    {
        "categoria": "Clientes",
        "nome": "Lista clientes com prazo",
        "method": "GET",
        "path": "/INTEGRACAO/INTEGRACAO_LISTA_CLIENTE_PRAZO",
        "pag": True,
    },
    {
        "categoria": "Clientes",
        "nome": "Centro de custo cliente",
        "method": "POST",
        "path": "/INTEGRACAO/CENTRO_CUSTO_CLIENTE",
        "body": True,
    },
    {
        "categoria": "Clientes",
        "nome": "Retorno cadastro cliente (GET + filtros no body na lib — use query)",
        "method": "GET",
        "path": "/INTEGRACAO/RETORNO_CADASTRO_CLIENTE",
        "dates": False,
        "pag": True,
    },
    {
        "categoria": "Clientes",
        "nome": "Integração cadastro cliente (consulta)",
        "method": "GET",
        "path": "/INTEGRACAO/INTEGRACAO_CLIENTE_CADASTRO",
        "pag": True,
    },
    # —— Financeiro / caixa ——
    {
        "categoria": "Financeiro",
        "nome": "Títulos a receber",
        "method": "GET",
        "path": "/INTEGRACAO/TITULO_RECEBER",
        "dates": True,
        "pag": True,
        "fil": True,
        "extra": {"situacaoReceber": "AMBOS|ABERTO|RECEBIDO"},
    },
    {
        "categoria": "Financeiro",
        "nome": "Criar título a receber",
        "method": "POST",
        "path": "/INTEGRACAO/TITULO_RECEBER",
        "body": True,
    },
    {
        "categoria": "Financeiro",
        "nome": "Títulos a pagar",
        "method": "GET",
        "path": "/INTEGRACAO/TITULO_PAGAR",
        "dates": True,
        "pag": True,
        "fil": True,
        "extra": {"situacaoPagar": ""},
    },
    {
        "categoria": "Financeiro",
        "nome": "Criar título a pagar",
        "method": "POST",
        "path": "/INTEGRACAO/TITULO_PAGAR",
        "body": True,
    },
    {
        "categoria": "Financeiro",
        "nome": "Receber título",
        "method": "PUT",
        "path": "/INTEGRACAO/RECEBER_TITULO",
        "body": True,
    },
    {
        "categoria": "Financeiro",
        "nome": "Receber título convertido",
        "method": "PUT",
        "path": "/INTEGRACAO/RECEBER_TITULO_CONVERTIDO",
        "body": True,
    },
    {
        "categoria": "Financeiro",
        "nome": "Receber cheque",
        "method": "PUT",
        "path": "/INTEGRACAO/RECEBER_CHEQUE",
        "body": True,
        "extra_query": {"empresaCodigo": "opcional query"},
    },
    {
        "categoria": "Financeiro",
        "nome": "Receber cartão",
        "method": "PUT",
        "path": "/INTEGRACAO/RECEBER_CARTAO",
        "body": True,
    },
    {
        "categoria": "Financeiro",
        "nome": "Movimento de conta",
        "method": "GET",
        "path": "/INTEGRACAO/MOVIMENTO_CONTA",
        "dates": True,
        "pag": True,
        "fil": True,
    },
    {
        "categoria": "Financeiro",
        "nome": "Fechamento de caixa (endpoint dedicado)",
        "method": "GET",
        "path": "/INTEGRACAO/FECHAMENTO_CAIXA",
        "dates": True,
        "pag": True,
        "fil": True,
    },
    {
        "categoria": "Financeiro",
        "nome": "Caixa (turnos / movimento)",
        "method": "GET",
        "path": "/INTEGRACAO/CAIXA",
        "dates": True,
        "pag": True,
        "fil": True,
    },
    {
        "categoria": "Financeiro",
        "nome": "Caixa apresentado × apurado",
        "method": "GET",
        "path": "/INTEGRACAO/CAIXA_APRESENTADO",
        "dates": True,
        "pag": True,
        "fil": True,
    },
    {
        "categoria": "Financeiro",
        "nome": "Transferência (integração legada)",
        "method": "GET",
        "path": "/INTEGRACAO/TRANSFERENCIA",
        "dates": True,
        "fil": True,
    },
    {
        "categoria": "Financeiro",
        "nome": "Transferência bancária",
        "method": "GET",
        "path": "/INTEGRACAO/TRANSFERENCIA_BANCARIA",
        "dates": True,
        "fil": True,
    },
    {
        "categoria": "Financeiro",
        "nome": "Criar transferência bancária",
        "method": "POST",
        "path": "/INTEGRACAO/TRANSFERENCIA_BANCARIA",
        "body": True,
    },
    {
        "categoria": "Financeiro",
        "nome": "Plano de contas",
        "method": "GET",
        "path": "/INTEGRACAO/PLANO_DE_CONTAS",
        "pag": True,
    },
    {
        "categoria": "Financeiro",
        "nome": "Financeiro exclusão (débito caixa)",
        "method": "GET",
        "path": "/INTEGRACAO/FINANCEIRO_EXCLUSAO",
        "dates": True,
        "fil": True,
    },
    {
        "categoria": "Financeiro",
        "nome": "Adiantamento fornecedor",
        "method": "GET",
        "path": "/INTEGRACAO/ADIANTAMENTO_FORNECEDOR",
        "dates": True,
        "fil": True,
    },
    {
        "categoria": "Financeiro",
        "nome": "Incluir lançamento contábil",
        "method": "POST",
        "path": "/INTEGRACAO/INCLUIR_LANCAMENTO_CONTABIL",
        "body": True,
    },
    {
        "categoria": "Financeiro",
        "nome": "Incluir lote contábil",
        "method": "POST",
        "path": "/INTEGRACAO/INCLUIR_LOTE_CONTABIL",
        "body": True,
    },
    {
        "categoria": "Financeiro",
        "nome": "Importar OFX",
        "method": "POST",
        "path": "/INTEGRACAO/INCLUIR_OFX",
        "body": True,
    },
    # —— Produtos / estoque ——
    {
        "categoria": "Produtos",
        "nome": "Listar produtos",
        "method": "GET",
        "path": "/INTEGRACAO/PRODUTO",
        "pag": True,
        "extra": {"codigo": "", "nome": ""},
    },
    {
        "categoria": "Produtos",
        "nome": "Criar produto",
        "method": "POST",
        "path": "/INTEGRACAO/PRODUTO",
        "body": True,
    },
    {
        "categoria": "Produtos",
        "nome": "Alterar produto",
        "method": "PUT",
        "path": "/INTEGRACAO/ALTERAR_PRODUTO/{id}",
        "path_params": ["id"],
        "body": True,
    },
    {
        "categoria": "Produtos",
        "nome": "Reajustar produto (%)",
        "method": "POST",
        "path": "/INTEGRACAO/REAJUSTAR_PRODUTO",
        "body": True,
    },
    {
        "categoria": "Produtos",
        "nome": "Troca preço produto",
        "method": "POST",
        "path": "/INTEGRACAO/TROCA_PRECO_PRODUTO",
        "body": True,
    },
    {
        "categoria": "Produtos",
        "nome": "Troca preço combustível",
        "method": "POST",
        "path": "/INTEGRACAO/TROCA_PRECO_COMBUSTIVEL",
        "body": True,
    },
    {
        "categoria": "Produtos",
        "nome": "Produto inventário",
        "method": "POST",
        "path": "/INTEGRACAO/PRODUTO_INVENTARIO",
        "body": True,
    },
    {
        "categoria": "Produtos",
        "nome": "Lista de itens (catálogo PRODUTO)",
        "method": "GET",
        "path": "/INTEGRACAO/PRODUTO",
        "pag": True,
    },
    {
        "categoria": "Produtos",
        "nome": "Itens inventário",
        "method": "GET",
        "path": "/INTEGRACAO/PRODUTO_INVENTARIO_ITENS",
        "pag": True,
    },
    {
        "categoria": "Produtos",
        "nome": "Ajuste estoque produto",
        "method": "POST",
        "path": "/INTEGRACAO/AJUSTE_ESTOQUE_PRODUTO",
        "body": True,
    },
    {
        "categoria": "Produtos",
        "nome": "Comissão produto",
        "method": "POST",
        "path": "/INTEGRACAO/PRODUTO_COMISSAO",
        "body": True,
    },
    {
        "categoria": "Produtos",
        "nome": "Tributo ICMS produtos",
        "method": "GET",
        "path": "/INTEGRACAO/INTEGRACAO_PRODUTO_TRIBUTO_ICMS",
        "pag": True,
    },
    {
        "categoria": "Produtos",
        "nome": "Tributo PIS/COFINS produtos",
        "method": "GET",
        "path": "/INTEGRACAO/INTEGRACAO_PRODUTO_TRIBUTO_PIS_CONFINS",
        "pag": True,
    },
    {
        "categoria": "Produtos",
        "nome": "Estoque (integração)",
        "method": "GET",
        "path": "/INTEGRACAO/ESTOQUE",
        "pag": False,
    },
    {
        "categoria": "Produtos",
        "nome": "Preço por produto",
        "method": "GET",
        "path": "/INTEGRACAO/PRECO_PRODUTO",
        "pag": False,
    },
    {
        "categoria": "Produtos",
        "nome": "Combustível (cadastro)",
        "method": "GET",
        "path": "/INTEGRACAO/COMBUSTIVEL",
        "pag": False,
    },
    {
        "categoria": "Produtos",
        "nome": "Retorno cadastro produto",
        "method": "GET",
        "path": "/INTEGRACAO/RETORNO_CADASTRO_PRODUTO",
        "pag": True,
    },
    # —— Vendas / NF / cadastros ——
    {
        "categoria": "Vendas & NF",
        "nome": "Vendas",
        "method": "GET",
        "path": "/INTEGRACAO/VENDA",
        "dates": True,
        "pag": True,
        "fil": True,
    },
    {
        "categoria": "Vendas & NF",
        "nome": "Vendas rede",
        "method": "GET",
        "path": "/INTEGRACAO/VENDA_REDE",
        "dates": True,
        "pag": True,
    },
    {
        "categoria": "Vendas & NF",
        "nome": "NF entrada",
        "method": "GET",
        "path": "/INTEGRACAO/NOTA_FISCAL_ENTRADA",
        "dates": True,
        "pag": True,
        "fil": True,
        "extra": {"distribuidora": "", "modeloDocumentoFiscal": ""},
    },
    {
        "categoria": "Vendas & NF",
        "nome": "NF saída",
        "method": "GET",
        "path": "/INTEGRACAO/NOTA_FISCAL_SAIDA",
        "dates": True,
        "pag": True,
        "fil": True,
    },
    {
        "categoria": "Vendas & NF",
        "nome": "Pedidos de compras",
        "method": "GET",
        "path": "/INTEGRACAO/PEDIDO_COMPRAS",
        "dates": True,
        "pag": True,
    },
    {
        "categoria": "Vendas & NF",
        "nome": "Criar pedido de compras",
        "method": "POST",
        "path": "/INTEGRACAO/PEDIDO_COMPRAS",
        "body": True,
    },
    {
        "categoria": "Vendas & NF",
        "nome": "Usuários",
        "method": "GET",
        "path": "/INTEGRACAO/USUARIO",
        "pag": True,
    },
    {
        "categoria": "Vendas & NF",
        "nome": "Usuário empresa rede",
        "method": "GET",
        "path": "/INTEGRACAO/USUARIO_EMPRESA_REDE",
        "pag": True,
    },
    {
        "categoria": "Vendas & NF",
        "nome": "Filiais",
        "method": "GET",
        "path": "/INTEGRACAO/FILIAL",
        "pag": True,
    },
    {
        "categoria": "Vendas & NF",
        "nome": "Administradoras",
        "method": "GET",
        "path": "/INTEGRACAO/ADMINISTRADORA",
        "pag": True,
    },
    {
        "categoria": "Vendas & NF",
        "nome": "Veículos (cadastro geral)",
        "method": "GET",
        "path": "/INTEGRACAO/VEICULO",
        "pag": True,
    },
    {
        "categoria": "Vendas & NF",
        "nome": "Prazo tabela preço",
        "method": "GET",
        "path": "/INTEGRACAO/PRAZO_TABELA_PRECO",
        "pag": True,
    },
    {
        "categoria": "Vendas & NF",
        "nome": "Item prazo tabela preço",
        "method": "POST",
        "path": "/INTEGRACAO/PRAZO_TABELA_PRECO/{tabela_id}/ITEM",
        "path_params": ["tabela_id"],
        "body": True,
    },
    {
        "categoria": "Vendas & NF",
        "nome": "Autorizar pagamento abastecimento",
        "method": "POST",
        "path": "/INTEGRACAO/AUTORIZA_PAGAMENTO_ABASTECIMENTO",
        "body": True,
    },
    {
        "categoria": "Vendas & NF",
        "nome": "Persistir cartão DTO",
        "method": "POST",
        "path": "/INTEGRACAO/PERSISTIR_CARTAO_DTO",
        "body": True,
    },
    # —— Pedido combustível ——
    {
        "categoria": "Pedido combustível",
        "nome": "Listar pedidos",
        "method": "GET",
        "path": "/INTEGRACAO/PEDIDO_COMBUSTIVEL/PEDIDO",
        "dates": True,
        "pag": True,
    },
    {
        "categoria": "Pedido combustível",
        "nome": "Criar pedido",
        "method": "POST",
        "path": "/INTEGRACAO/PEDIDO_COMBUSTIVEL/PEDIDO",
        "body": True,
    },
    {
        "categoria": "Pedido combustível",
        "nome": "Faturar pedido",
        "method": "POST",
        "path": "/INTEGRACAO/PEDIDO_COMBUSTIVEL/PEDIDO/{pedido_id}/FATURAR",
        "path_params": ["pedido_id"],
        "body": False,
    },
    {
        "categoria": "Pedido combustível",
        "nome": "Vincular cliente pedido",
        "method": "POST",
        "path": "/INTEGRACAO/PEDIDO_COMBUSTIVEL/CLIENTE",
        "body": True,
    },
    {
        "categoria": "Pedido combustível",
        "nome": "Receber título pedido em cartão",
        "method": "PUT",
        "path": "/INTEGRACAO/PEDIDO_COMBUSTIVEL/PEDIDO/{pedido_id}/RECEBER_TITULO_EM_CARTAO",
        "path_params": ["pedido_id"],
        "body": True,
    },
    {
        "categoria": "Pedido combustível",
        "nome": "APRIX custo",
        "method": "GET",
        "path": "/INTEGRACAO/APRIX_CUSTO",
        "dates": True,
        "pag": True,
        "fil": True,
    },
    {
        "categoria": "Pedido combustível",
        "nome": "LMC",
        "method": "GET",
        "path": "/INTEGRACAO/LMC",
        "dates": True,
        "pag": True,
        "fil": True,
    },
    {
        "categoria": "Pedido combustível",
        "nome": "Distribuidoras",
        "method": "GET",
        "path": "/INTEGRACAO/DISTRIBUIDORA",
        "pag": True,
    },
    # —— Relatórios ——
    {
        "categoria": "Relatórios",
        "nome": "Rel. venda produto",
        "method": "GET",
        "path": "/INTEGRACAO/RELATORIO/VENDA_PRODUTO",
        "dates": True,
        "pag": True,
        "fil": True,
        "extra": {"produto": "lista códigos"},
    },
    {
        "categoria": "Relatórios",
        "nome": "Rel. venda combustível",
        "method": "GET",
        "path": "/INTEGRACAO/RELATORIO/VENDA_COMBUSTIVEL",
        "dates": True,
        "pag": True,
        "fil": True,
    },
    {
        "categoria": "Relatórios",
        "nome": "Resumo vendas",
        "method": "GET",
        "path": "/INTEGRACAO/RELATORIO/RESUMO_VENDAS",
        "dates": True,
        "fil": True,
    },
    {
        "categoria": "Relatórios",
        "nome": "Rel. estoque",
        "method": "GET",
        "path": "/INTEGRACAO/RELATORIO/ESTOQUE",
        "pag": True,
        "fil": True,
        "extra": {"produto": ""},
    },
]
